# Generated by Django 4.1.2 on 2022-10-11 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                (
                    'profile_image',
                    models.ImageField(
                        default='default_profile_image.png',
                        upload_to='profile_images',
                    ),
                ),
                ('location', models.CharField(blank=True, max_length=250)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
